package com.empiretycoon.idleconquest.ui

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.view.MotionEvent
import android.view.View
import com.empiretycoon.idleconquest.art.*
import com.empiretycoon.idleconquest.game.*
import java.util.Locale

class BusinessShowcaseView(context:Context):View(context){
 private val screenBackground=ScreenBackgroundRenderer(context);private val empireLogo=EmpireLogoRenderer(context);private val resolver=BusinessArtResolver(context);private val layers=BusinessLayerRenderer(context);private val sprites=ProceduralBusinessSpriteRenderer(context);private val businessCards=BusinessCardStateRenderer(context);private val stateOverlays=BuildingStateOverlayRenderer(context);private val hudPanels=HudPanelRenderer(context);private val portraits=ManagerPortraitRenderer(context);private val permanentIcons=PermanentUpgradeIconRenderer(context);private val missionBadges=MissionBadgeRenderer(context);private val prestigeIcon=PrestigeIconRenderer(context);private val currencyIcons=CurrencyIconRenderer(context);private val controlSprites=ControlSpriteRenderer(context);private val statIcons=BusinessStatIconRenderer(context);private val saveStore=GameSaveStore(context);private var gameState:GameState;private lateinit var interactions:UiInteractionController
 private val paint=Paint(Paint.ANTI_ALIAS_FLAG);private val upgradeRects=mutableListOf<RectF>();private val managerRects=mutableListOf<Pair<String,RectF>>();private val permanentRects=mutableListOf<Pair<String,RectF>>();private val missionRects=mutableListOf<Pair<String,RectF>>();private val modeRects=mutableListOf<Pair<BuyMode,RectF>>();private var prestigeRect=RectF();private var buyMode=BuyMode.X1;private var lastFrame=0L;private var lastSave=0L;private var banner:String?=null;private var bannerUntil=0L;private var highlighted:String?=null
 init{val r=saveStore.restore();gameState=r.state;interactions=UiInteractionController(gameState);if(r.offlineEarnings>0)show("WELCOME BACK +$ ${fmt(r.offlineEarnings)}",6_000_000_000L);isClickable=true;keepScreenOn=false}
 override fun onDraw(c:Canvas){super.onDraw(c);update();autosave();screenBackground.draw(c,width,height);val m=width*.04f;val hh=height*.09f;val mh=height*.045f;val qh=height*.07f;hud(c,RectF(m,m,width-m,m+hh));modes(c,RectF(m,m+hh+5,width-m,m+hh+5+mh));missions(c,RectF(m,m+hh+mh+10,width-m,m+hh+mh+10+qh));val now=System.nanoTime();val bh=if(banner!=null&&now<bannerUntil)height*.038f else 0f;if(bh>0)banner(c,RectF(m,m+hh+mh+qh+16,width-m,m+hh+mh+qh+16+bh),banner!!);upgradeRects.clear();managerRects.clear();permanentRects.clear();val top=m+hh+mh+qh+m+bh;val gap=m*.4f;val ch=(height-top-m-gap*3)/4;gameState.businesses.indices.forEach{i->card(c,RectF(m,top+i*(ch+gap),width-m,top+i*(ch+gap)+ch),i,now)};postInvalidateDelayed(50L)}
 private fun update(){val n=System.nanoTime();if(lastFrame!=0L)gameState.tick(((n-lastFrame)/1e9).coerceAtMost(.25));lastFrame=n}
 private fun autosave(){val n=System.nanoTime();if(lastSave==0L||n-lastSave>=10_000_000_000L){saveStore.save(gameState);lastSave=n}}
 fun persistNow()=saveStore.save(gameState)
 private fun hud(c:Canvas,r:RectF){hudPanels.draw(c,r,"hud");val logoH=r.height()*.36f;val logoW=logoH*4f;empireLogo.draw(c,RectF(r.left+18f,r.top+6f,r.left+18f+logoW,r.top+6f+logoH));paint.textSize=width*.027f;val isz=r.height()*.25f;val cashR=RectF(r.left+20,r.bottom-16-isz,r.left+20+isz,r.bottom-16);currencyIcons.draw(c,cashR,"cash");paint.color=Color.WHITE;c.drawText(fmt(gameState.cash),cashR.right+6,r.bottom-14,paint);paint.color=Color.rgb(92,230,145);c.drawText("+${fmt(gameState.totalIncomePerSecond)}/s",r.centerX()-20,r.bottom-14,paint);val size=r.height()*.78f;prestigeRect=RectF(r.right-size-8f,r.top+r.height()*.11f,r.right-8f,r.top+r.height()*.89f);val q=gameState.prestigeQuote();prestigeIcon.draw(c,prestigeRect,UiVisualStateMapper.prestige(q.available,gameState.prestigeCrowns),gameState.prestigeCrowns);paint.textAlign=Paint.Align.RIGHT;paint.color=Color.rgb(245,201,92);paint.textSize=width*.021f;c.drawText("x${mult(gameState.prestigeMultiplier)}",prestigeRect.left-6f,r.top+r.height()*.35f,paint);val gemR=RectF(prestigeRect.left-isz-58,r.bottom-16-isz,prestigeRect.left-58,r.bottom-16);currencyIcons.draw(c,gemR,"gem");paint.color=Color.rgb(120,187,255);c.drawText(gameState.gems.toString(),gemR.left-5f,r.bottom-14,paint);paint.textAlign=Paint.Align.LEFT}
 private fun modes(c:Canvas,r:RectF){modeRects.clear();val gap=7f;val w=(r.width()-gap*3)/4;BuyMode.entries.forEachIndexed{i,x->val b=RectF(r.left+i*(w+gap),r.top,r.left+i*(w+gap)+w,r.bottom);modeRects+=x to b;val base=when(x){BuyMode.X1->"x1";BuyMode.X10->"x10";BuyMode.X25->"x25";BuyMode.MAX->"max"};controlSprites.draw(c,b,"${base}_${if(x==buyMode)"on" else "off"}")}}
 private fun missions(c:Canvas,r:RectF){missionRects.clear();hudPanels.draw(c,r,"missions");val list=gameState.missions;val gap=5f;val w=(r.width()-gap*5)/6f;list.forEachIndexed{i,m->val rr=RectF(r.left+i*(w+gap),r.top,r.left+i*(w+gap)+w,r.bottom);val state=UiVisualStateMapper.mission(m.claimed,m.completed,m.progress);missionBadges.draw(c,rr,m.definition,state);missionRects+=m.definition.id to rr}}
 private fun banner(c:Canvas,r:RectF,t:String){hudPanels.draw(c,r,"banner");paint.color=Color.rgb(255,220,112);paint.textAlign=Paint.Align.CENTER;paint.isFakeBoldText=true;paint.textSize=width*.023f;c.drawText(t,r.centerX(),r.centerY()+paint.textSize*.35f,paint);paint.textAlign=Paint.Align.LEFT;paint.isFakeBoldText=false}
 private fun card(c:Canvas,r:RectF,i:Int,now:Long){val b=gameState.businesses[i];val tier=gameState.tierFor(b.level);val active=highlighted==b.id&&now<bannerUntil;val state=if(active)"milestone" else "default";val art=resolver.resolve(b.id,tier,state=state);val cardState=UiVisualStateMapper.businessCard(active,gameState.canUpgrade(i,buyMode));businessCards.draw(c,r,cardState);val inset=10f;val artR=RectF(r.left+inset,r.top+inset,r.left+r.width()*.24f,r.bottom-inset);if(!layers.draw(c,artR,art.layerPaths))sprites.draw(c,artR,b.id,tier,state);if(active)stateOverlays.drawMilestone(c,artR);val x=r.left+r.width()*.28f;val rightColLeft=r.right-r.width()*.19f;val manager=gameState.managerFor(b.id)!!;val pr=RectF(rightColLeft,r.top+inset,r.right-inset,r.top+r.height()*.45f);val managerState=UiVisualStateMapper.manager(manager.hired,b.level,manager.definition.unlockLevel);portraits.draw(c,pr,manager.definition,managerState);managerRects+=manager.definition.id to pr;drawPermanentUpgrades(c,r,b,rightColLeft,inset);paint.style=Paint.Style.FILL;paint.color=Color.WHITE;paint.textSize=width*.027f;paint.isFakeBoldText=true;c.drawText(b.displayName,x,r.top+r.height()*.18f,paint);paint.isFakeBoldText=false;paint.textSize=width*.0195f;val isz=r.height()*.085f;val tx=x+isz+5f;val y1=r.top+r.height()*.31f;val y2=r.top+r.height()*.44f;val y3=r.top+r.height()*.57f;val y4=r.top+r.height()*.68f;statIcons.draw(c,RectF(x,y1-isz*.78f,x+isz,y1+isz*.22f),"level");paint.color=Color.rgb(188,198,225);c.drawText("Lv.${b.level} • ${tier.uppercase(Locale.US)} • ×${mult(b.productionMultiplier)}",tx,y1,paint);statIcons.draw(c,RectF(x,y2-isz*.78f,x+isz,y2+isz*.22f),"income");paint.color=Color.rgb(92,230,145);c.drawText("+${fmt(gameState.incomeFor(b))}/s",tx,y2,paint);statIcons.draw(c,RectF(x,y3-isz*.78f,x+isz,y3+isz*.22f),"manager");paint.color=Color.rgb(120,187,255);val mt=if(manager.hired)"${manager.definition.name} ×${mult(manager.definition.incomeMultiplier)}" else if(b.level>=manager.definition.unlockLevel)"HIRE ${manager.definition.name} $${fmt(manager.definition.cost)}" else "MANAGER Lv.${manager.definition.unlockLevel}";c.drawText(mt,tx,y3,paint);val pm=gameState.permanentIncomeMultiplier(b.id);val cm=gameState.permanentCostMultiplier(b.id);statIcons.draw(c,RectF(x,y4-isz*.78f,x+isz,y4+isz*.22f),"permanent");paint.color=Color.rgb(245,201,92);c.drawText("PERM income ×${mult(pm)} • cost ×${mult(cm)}",tx,y4,paint);val br=RectF(x,r.bottom-r.height()*.22f,rightColLeft-8f,r.bottom-inset);upgradeRects+=br;upgradeButton(c,br,i)}
 private fun drawPermanentUpgrades(c:Canvas,r:RectF,b:BusinessState,left:Float,inset:Float){val list=gameState.permanentUpgrades.filter{it.definition.businessId==b.id};val gap=5f;val top=r.top+r.height()*.49f;val h=(r.bottom-inset-top-gap)/2f;list.forEachIndexed{idx,u->val rr=RectF(left,top+idx*(h+gap),r.right-inset,top+idx*(h+gap)+h);val state=UiVisualStateMapper.permanentUpgrade(u.purchased,b.level,u.definition.unlockLevel);permanentIcons.draw(c,rr,u.definition.id,state);permanentRects+=u.definition.id to rr}}
 private fun upgradeButton(c:Canvas,r:RectF,i:Int){controlSprites.draw(c,r,if(gameState.canUpgrade(i,buyMode))"upgrade_on" else "upgrade_off")}
 override fun onTouchEvent(e:MotionEvent):Boolean{if(e.action==MotionEvent.ACTION_UP){if(prestigeRect.contains(e.x,e.y)){applyInteraction(interactions.prestige());return finishTap()};missionRects.firstOrNull{it.second.contains(e.x,e.y)}?.let{applyInteraction(interactions.mission(it.first));return finishTap()};modeRects.firstOrNull{it.second.contains(e.x,e.y)}?.let{buyMode=it.first;return finishTap()};permanentRects.firstOrNull{it.second.contains(e.x,e.y)}?.let{applyInteraction(interactions.permanentUpgrade(it.first));return finishTap()};managerRects.firstOrNull{it.second.contains(e.x,e.y)}?.let{applyInteraction(interactions.manager(it.first));return finishTap()};val i=upgradeRects.indexOfFirst{it.contains(e.x,e.y)};if(i>=0){applyInteraction(interactions.businessUpgrade(i,buyMode));return finishTap()}};return true}
 private fun applyInteraction(result:UiInteractionResult){if(result.clearHighlight)highlighted=null;result.highlightBusinessId?.let{highlighted=it};result.message?.let{show(it,result.durationNanos)};if(result.saveRequired)saveStore.save(gameState)}
 private fun finishTap():Boolean{performClick();invalidate();return true}
 override fun performClick():Boolean{super.performClick();return true}
 private fun show(t:String,d:Long){banner=t;bannerUntil=System.nanoTime()+d}
 private fun mult(v:Double)=UiNumberFormatter.multiplier(v)
 private fun fmt(v:Double)=UiNumberFormatter.compact(v)
}
