package com.empiretycoon.idleconquest.ui

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.view.MotionEvent
import android.view.View
import com.empiretycoon.idleconquest.art.*
import com.empiretycoon.idleconquest.game.*

class BusinessShowcaseView(context:Context):View(context){
 private val screenBackground=ScreenBackgroundRenderer(context);private val empireLogo=EmpireLogoRenderer(context);private val resolver=BusinessArtResolver(context);private val layers=BusinessLayerRenderer(context);private val sprites=ProceduralBusinessSpriteRenderer(context);private val businessCards=BusinessCardStateRenderer(context);private val stateOverlays=BuildingStateOverlayRenderer(context);private val hudPanels=HudPanelRenderer(context);private val portraits=ManagerPortraitRenderer(context);private val permanentIcons=PermanentUpgradeIconRenderer(context);private val missionBadges=MissionBadgeRenderer(context);private val prestigeIcon=PrestigeIconRenderer(context);private val currencyIcons=CurrencyIconRenderer(context);private val controlSprites=ControlSpriteRenderer(context);private val statIcons=BusinessStatIconRenderer(context);private val saveStore=GameSaveStore(context);private val transientState=UiTransientState();private val backgroundSession=BackgroundSessionProgress();private var gameState:GameState;private lateinit var interactions:UiInteractionController
 private val paint=Paint(Paint.ANTI_ALIAS_FLAG);private val upgradeRects=mutableListOf<RectF>();private val managerRects=mutableListOf<Pair<String,RectF>>();private val permanentRects=mutableListOf<Pair<String,RectF>>();private val missionRects=mutableListOf<Pair<String,RectF>>();private val modeRects=mutableListOf<Pair<BuyMode,RectF>>();private var prestigeRect=RectF();private var buyMode=BuyMode.X1;private var lastFrame=0L;private var lastSave=0L
 init{val r=saveStore.restore();gameState=r.state;interactions=UiInteractionController(gameState);if(r.offlineEarnings>0)show("WELCOME BACK +$ ${fmt(r.offlineEarnings)}",6_000_000_000L);isClickable=true;keepScreenOn=false}
 override fun onDraw(c:Canvas){super.onDraw(c);update();autosave();screenBackground.draw(c,width,height);val now=System.nanoTime();val bannerText=transientState.bannerAt(now);val layout=ShowcaseLayout.frame(width,height,bannerText!=null,gameState.businesses.size);hud(c,rect(layout.hud));modes(c,rect(layout.modes));missions(c,rect(layout.missions));layout.banner?.let{bounds->bannerText?.let{text->banner(c,rect(bounds),text)}};upgradeRects.clear();managerRects.clear();permanentRects.clear();layout.businessCards.forEachIndexed{i,bounds->card(c,rect(bounds),i,now)};postInvalidateDelayed(50L)}
 private fun update(){val n=System.nanoTime();if(lastFrame!=0L)gameState.tick(((n-lastFrame)/1e9).coerceAtMost(.25));lastFrame=n}
 private fun autosave(){val n=System.nanoTime();if(lastSave==0L||n-lastSave>=10_000_000_000L){saveStore.save(gameState);lastSave=n}}
 fun persistNow(nowEpochMillis:Long=System.currentTimeMillis())=saveStore.save(gameState,backgroundSession.saveTimestamp(nowEpochMillis))
 fun pauseForBackground(nowEpochMillis:Long=System.currentTimeMillis()){backgroundSession.markPaused(nowEpochMillis);lastFrame=0L;persistNow(nowEpochMillis)}
 fun resumeFromBackground(nowEpochMillis:Long=System.currentTimeMillis()){val offline=backgroundSession.consumeResume(nowEpochMillis,gameState.totalIncomePerSecond)?:return;lastFrame=0L;if(offline.earnings>0.0){gameState.addCash(offline.earnings,true);show("WELCOME BACK +$ ${fmt(offline.earnings)}",6_000_000_000L)};saveStore.save(gameState,nowEpochMillis);invalidate()}
 private fun hud(c:Canvas,r:RectF){hudPanels.draw(c,r,"hud");val logoH=r.height()*.36f;val logoW=logoH*4f;empireLogo.draw(c,RectF(r.left+18f,r.top+6f,r.left+18f+logoW,r.top+6f+logoH));paint.textSize=width*.027f;val isz=r.height()*.25f;val cashR=RectF(r.left+20,r.bottom-16-isz,r.left+20+isz,r.bottom-16);currencyIcons.draw(c,cashR,"cash");paint.color=Color.WHITE;c.drawText(fmt(gameState.cash),cashR.right+6,r.bottom-14,paint);paint.color=Color.rgb(92,230,145);c.drawText("+${fmt(gameState.totalIncomePerSecond)}/s",r.centerX()-20,r.bottom-14,paint);val size=r.height()*.78f;prestigeRect=RectF(r.right-size-8f,r.top+r.height()*.11f,r.right-8f,r.top+r.height()*.89f);val q=gameState.prestigeQuote();prestigeIcon.draw(c,prestigeRect,UiVisualStateMapper.prestige(q.available,gameState.prestigeCrowns),gameState.prestigeCrowns);paint.textAlign=Paint.Align.RIGHT;paint.color=Color.rgb(245,201,92);paint.textSize=width*.021f;c.drawText("x${mult(gameState.prestigeMultiplier)}",prestigeRect.left-6f,r.top+r.height()*.35f,paint);val gemR=RectF(prestigeRect.left-isz-58,r.bottom-16-isz,prestigeRect.left-58,r.bottom-16);currencyIcons.draw(c,gemR,"gem");paint.color=Color.rgb(120,187,255);c.drawText(gameState.gems.toString(),gemR.left-5f,r.bottom-14,paint);paint.textAlign=Paint.Align.LEFT}
 private fun modes(c:Canvas,r:RectF){modeRects.clear();val modes=BuyMode.entries;val slots=HorizontalSlotLayout.calculate(UiBounds(r.left,r.top,r.right,r.bottom),modes.size,7f);modes.zip(slots).forEach{(x,bounds)->val b=rect(bounds);modeRects+=x to b;val base=when(x){BuyMode.X1->"x1";BuyMode.X10->"x10";BuyMode.X25->"x25";BuyMode.MAX->"max"};controlSprites.draw(c,b,"${base}_${if(x==buyMode)"on" else "off"}")}}
 private fun missions(c:Canvas,r:RectF){missionRects.clear();hudPanels.draw(c,r,"missions");val list=gameState.missions;val slots=HorizontalSlotLayout.calculate(UiBounds(r.left,r.top,r.right,r.bottom),list.size,5f);list.zip(slots).forEach{(m,bounds)->val rr=rect(bounds);val state=UiVisualStateMapper.mission(m.claimed,m.completed,m.progress);missionBadges.draw(c,rr,m.definition,state);missionRects+=m.definition.id to rr}}
 private fun banner(c:Canvas,r:RectF,t:String){hudPanels.draw(c,r,"banner");paint.color=Color.rgb(255,220,112);paint.textAlign=Paint.Align.CENTER;paint.isFakeBoldText=true;paint.textSize=width*.023f;c.drawText(t,r.centerX(),r.centerY()+paint.textSize*.35f,paint);paint.textAlign=Paint.Align.LEFT;paint.isFakeBoldText=false}
 private fun card(c:Canvas,r:RectF,i:Int,now:Long){val b=gameState.businesses[i];val upgrades=gameState.permanentUpgrades.filter{it.definition.businessId==b.id};val geometry=BusinessCardLayout.calculate(UiBounds(r.left,r.top,r.right,r.bottom),upgrades.size);val tier=gameState.tierFor(b.level);val active=transientState.isHighlighted(b.id,now);val state=if(active)"milestone" else "default";val art=resolver.resolve(b.id,tier,state=state);val cardState=UiVisualStateMapper.businessCard(active,gameState.canUpgrade(i,buyMode));businessCards.draw(c,r,cardState);val artR=rect(geometry.art);if(!layers.draw(c,artR,art.layerPaths))sprites.draw(c,artR,b.id,tier,state);if(active)stateOverlays.drawMilestone(c,artR);val manager=gameState.managerFor(b.id);val managerRect=rect(geometry.manager);if(manager!=null){val managerState=UiVisualStateMapper.manager(manager.hired,b.level,manager.definition.unlockLevel);portraits.draw(c,managerRect,manager.definition,managerState);managerRects+=manager.definition.id to managerRect};drawPermanentUpgrades(c,b,upgrades,geometry.permanentUpgradeSlots);paint.style=Paint.Style.FILL;paint.color=Color.WHITE;paint.textSize=width*.027f;paint.isFakeBoldText=true;c.drawText(b.displayName,geometry.contentLeft,geometry.titleY,paint);paint.isFakeBoldText=false;paint.textSize=width*.0195f;val isz=geometry.statIconSize;val x=geometry.contentLeft;val tx=geometry.textLeft;val y1=geometry.levelY;val y2=geometry.incomeY;val y3=geometry.managerY;val y4=geometry.permanentY;statIcons.draw(c,RectF(x,y1-isz*.78f,x+isz,y1+isz*.22f),"level");paint.color=Color.rgb(188,198,225);c.drawText(BusinessCardTextFormatter.level(b.level,tier,b.productionMultiplier),tx,y1,paint);statIcons.draw(c,RectF(x,y2-isz*.78f,x+isz,y2+isz*.22f),"income");paint.color=Color.rgb(92,230,145);c.drawText(BusinessCardTextFormatter.income(gameState.incomeFor(b)),tx,y2,paint);statIcons.draw(c,RectF(x,y3-isz*.78f,x+isz,y3+isz*.22f),"manager");paint.color=Color.rgb(120,187,255);val mt=manager?.let{BusinessCardTextFormatter.manager(it.definition.name,it.hired,b.level,it.definition.unlockLevel,it.definition.cost,it.definition.incomeMultiplier)}?:BusinessCardTextFormatter.manager(null,false,b.level,0,0.0,1.0);c.drawText(mt,tx,y3,paint);val pm=gameState.permanentIncomeMultiplier(b.id);val cm=gameState.permanentCostMultiplier(b.id);statIcons.draw(c,RectF(x,y4-isz*.78f,x+isz,y4+isz*.22f),"permanent");paint.color=Color.rgb(245,201,92);c.drawText(BusinessCardTextFormatter.permanent(pm,cm),tx,y4,paint);val upgradeRect=rect(geometry.upgradeButton);upgradeRects+=upgradeRect;upgradeButton(c,upgradeRect,i)}
 private fun drawPermanentUpgrades(c:Canvas,b:BusinessState,upgrades:List<PermanentUpgradeState>,slots:List<UiBounds>){upgrades.zip(slots).forEach{(u,bounds)->val rr=rect(bounds);val state=UiVisualStateMapper.permanentUpgrade(u.purchased,b.level,u.definition.unlockLevel);permanentIcons.draw(c,rr,u.definition.id,state);permanentRects+=u.definition.id to rr}}
 private fun upgradeButton(c:Canvas,r:RectF,i:Int){controlSprites.draw(c,r,if(gameState.canUpgrade(i,buyMode))"upgrade_on" else "upgrade_off")}
 override fun onTouchEvent(e:MotionEvent):Boolean{if(e.action==MotionEvent.ACTION_UP){if(prestigeRect.contains(e.x,e.y)){applyInteraction(interactions.prestige());return finishTap()};missionRects.firstOrNull{it.second.contains(e.x,e.y)}?.let{applyInteraction(interactions.mission(it.first));return finishTap()};modeRects.firstOrNull{it.second.contains(e.x,e.y)}?.let{buyMode=it.first;return finishTap()};permanentRects.firstOrNull{it.second.contains(e.x,e.y)}?.let{applyInteraction(interactions.permanentUpgrade(it.first));return finishTap()};managerRects.firstOrNull{it.second.contains(e.x,e.y)}?.let{applyInteraction(interactions.manager(it.first));return finishTap()};val i=upgradeRects.indexOfFirst{it.contains(e.x,e.y)};if(i>=0){applyInteraction(interactions.businessUpgrade(i,buyMode));return finishTap()}};return true}
 private fun applyInteraction(result:UiInteractionResult){val now=System.nanoTime();if(result.clearHighlight)transientState.clearHighlight();result.highlightBusinessId?.let{transientState.highlightBusiness(it,result.durationNanos,now)};result.message?.let{transientState.showBanner(it,result.durationNanos,now)};if(result.saveRequired)saveStore.save(gameState)}
 private fun finishTap():Boolean{performClick();invalidate();return true}
 private fun rect(bounds:UiBounds)=RectF(bounds.left,bounds.top,bounds.right,bounds.bottom)
 override fun performClick():Boolean{super.performClick();return true}
 private fun show(t:String,d:Long){transientState.showBanner(t,d,System.nanoTime())}
 private fun mult(v:Double)=UiNumberFormatter.multiplier(v)
 private fun fmt(v:Double)=UiNumberFormatter.compact(v)
}
